---
- name: Ensure volume directories exist for gitea.
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ gitea_volumes_dir }}/data"
    - "{{ gitea_volumes_dir }}/config"

- name: Create Podman network for gitea.
  containers.podman.podman_network:
    name: "{{ gitea_net_name }}"
    state: present

- name: Pull gitea image
  containers.podman.podman_image:
    name: "{{ gitea_app_image_name }}"
    tag: "{{ gitea_app_image_tag }}"
    state: present

- name: Create pod for gitea.
  containers.podman.podman_pod:
    name: "{{ gitea_pod_name }}"
    state: created
    userns: "keep-id:uid=1000"
    recreate: true
    publish:
      - "{{ gitea_publish_http }}:3000"
      - "{{ gitea_publish_ssh }}:2222"
    network:
      - "{{ gitea_net_name }}"

- name: Create gitea container
  containers.podman.podman_container:
    pod: "{{ gitea_pod_name }}"
    name: "{{ gitea_container_name }}"
    image: "{{ gitea_app_image_name }}:{{ gitea_app_image_tag }}"
    state: created
    restart_policy: always
    volume:
      - "{{ gitea_volumes_dir }}/data:/var/lib/gitea:Z"
      - "{{ gitea_volumes_dir }}/config:/etc/gitea:Z"
      - /etc/localtime:/etc/localtime:ro
    env:
      GITEA__database__DB_TYPE: "{{ gitea_db_type }}"
      GITEA__database__HOST: "{{ gitea_db_host }}:{{ gitea_db_port }}"
      GITEA__database__NAME: "{{ gitea_db_name }}"
      GITEA__database__USER: "{{ gitea_db_user }}"
      GITEA__database__PASSWD: "{{ gitea_db_pass }}"

- name: Create systemd service for gitea pod.
  containers.podman.podman_generate_systemd:
    name: "{{ gitea_pod_name }}"
    dest: /home/{{ gitea_user }}/.config/systemd/user
    restart_policy: on-failure
    force: true

- name: Ensure systemd service is enabled and started for gitea pod.
  ansible.builtin.systemd:
    scope: user
    name: "pod-{{ gitea_pod_name }}"
    daemon_reload: true
    state: started
    enabled: true
