---
- name: Include setup tasks.
  ansible.builtin.include_tasks: setup.yml

- name: Run tasks as user.
  become: true
  become_user: "{{ gitea_user }}"
  block:
    - name: Include app tasks.
      ansible.builtin.include_tasks: app.yml
