---
- name: Create a user named git.
  become: true
  when: gitea_user_create
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    state: present
    comment: "Git Version Control"
    home: /home/{{ gitea_user }}
    shell: /bin/bash
  register: user_data

- name: Check if gitea user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ gitea_user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ gitea_user }}"
  changed_when: true
  when: "gitea_user not in linger.stdout"
