---
- name: Create a user named git.
  become: true
  ansible.builtin.user:
    name: git
    state: present
    password: '!'
    comment: "Git Version Control"
    home: /home/git
    shell: /bin/bash
  register: user_data

- name: Set facts for UID and GID of git user.
  ansible.builtin.set_fact:
    gitea_uid: "{{ user_data.uid }}"
    gitea_gid: "{{ user_data.group }}"

- name: Check if gitea user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ gitea_user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ gitea_user }}"
  changed_when: true
  when: "gitea_user not in linger.stdout"
