---
- name: Converge
  hosts: all

  vars_files:
    - vars/main.yml
    - vars/postgres.yml

  tasks:
    - name: Ensure required volume dirs are created.
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        owner: "{{ gitea_user }}"
        group: "{{ gitea_user }}"
        state: directory
        setype: container_file_t
      loop:
        - "{{ gitea_volumes_dir }}"

    - name: "Include gitea"
      ansible.builtin.include_role:
        name: gitea
